### PR TITLE
Start Checkout Flow

### PR DESCRIPTION
**Pull request by ChristoPy**
Create Contact form to gather basic Customer information.
Create Address form to gather Customer address.
This allows for the next step: showing the OpenPIX payment screen with the Credit feature.

## Cart view
Screenshot from 2023-04-13 15-31-13
## Contact Information view
Screenshot from 2023-04-13 15-31-18
## Shipment Information view
Screenshot from 2023-04-13 15-31-32

### CODE REVIEW

**Comment by vinibgoulart** [comment]
nice!

try to avoid `index.tsx`, prefer `button/button.tsx` instead `button/index.tsx`...
use the index to make imports and exports

**Review by daniloab — APPROVED** [review]
add prints to the pr when having ui on that

**Comment by ChristoPy** [comment]
I'll do it

**Comment by ChristoPy** [comment]
> nice!
> 
> try to avoid `index.tsx`, prefer `button/button.tsx` instead `button/index.tsx`... use the index to make imports and exports

Thanks, I forgot to reuse the pattern.

**Pull request merged**
